# Generated by Django 4.2.7 on 2023-11-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duuni_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='programming_languages',
        ),
        migrations.AddField(
            model_name='joblisting',
            name='programming_languages',
            field=models.ManyToManyField(to='duuni_app.programminglanguage'),
        ),
    ]
