# Generated by Django 4.2.7 on 2023-12-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duuni_app', '0002_programminglanguage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_languages', models.JSONField()),
            ],
        ),
    ]
