# Generated by Django 4.2.7 on 2023-12-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duuni_app', '0003_languagearray'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LanguageArray',
            new_name='YourModel',
        ),
        migrations.RenameField(
            model_name='yourmodel',
            old_name='programming_languages',
            new_name='string_array',
        ),
    ]
