# Generated by Django 4.2.7 on 2023-12-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duuni_app', '0004_rename_languagearray_yourmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='string_array',
            field=models.CharField(max_length=20),
        ),
    ]
