# Generated by Django 4.2.7 on 2023-12-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duuni_app', '0005_alter_yourmodel_string_array'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
